platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: pal-tracker
  - name: version

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
    cd pal-tracker
    chmod +x gradlew
    ./gradlew -P version=$(cat ../version/number) build
<<<<<<< HEAD
    cp build/libs/pal-tracker-*.jar ../build-output
=======
    cp build/libs/pal-tracker-*.jar ../build-output
>>>>>>> b28134d5e6788ac6ef8ba5e82a8b4b7fbdfa62e7
